version: '3.9'

services:
  database:
    image: mysql
    container_name: laravel_db
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
    volumes:
      - $PROJECT_PATH/mysql:/var/lib/mysql
    # healthcheck:
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #   timeout: 5s
    #   retries: 20
  myapp:
    image: bitnami/laravel:$LARAVEL_VERSION 
    ports:
      - $LARAVEL_APP_PORT:$LARAVEL_INTERNAL_PORT
    container_name: laravel_app
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USERNAME=$DB_USERNAME
      - DB_DATABASE=$DB_DATABASE
      - DB_PASSWORD=$DB_PASSWORD
    volumes:
      - $PROJECT_PATH/website:/app
    # depends_on:
    #   database:
    #     condition: service_healthy
  mailhog:
    platform: linux/x86_64
    image: mailhog/mailhog
    container_name: laravel_smtp
    logging:
      driver: 'none'
    ports:
      - "8003:1025"
      - "8100:8025"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    ports:
      - $PHP_MY_ADMIN_PORT:80
    environment:
      - PMA_HOST=database
    depends_on:
      - database
