version: '2'

services:
  database:
    image: mysql
    container_name: laravel_db
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - $PROJECT_PATH/mysql:/var/lib/mysql
  myapp:
    image: bitnami/laravel:$LARAVEL_VERSION 
    ports:
      - $LARAVEL_APP_PORT:3000
    container_name: laravel_app
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USERNAME=$DB_USERNAME
      - DB_DATABASE=$DB_DATABASE
      - DB_PASSWORD=$DB_PASSWORD
    volumes:
      - $PROJECT_PATH/website:/app
    depends_on:
      - database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    ports:
      - $PHP_MY_ADMIN_PORT:80
    environment:
      - PMA_HOST=database
    depends_on:
      - database
